.github/workflows/main.yml, controllers/securesign_controller.go, hack/router-crd.yaml
Test to ensure deployments are in an available state and always dump the operator logs to show any issues that may exist
=> deployment tests 

.github/workflows/main.yml, hack/connection-verify.yaml, hack/cosign-createcertns.yaml, hack/cosign-testns.yaml
test connectivity to created resources
=> test connection pod

OWNERS
@cooktheryan we need this to onboard to openshift CI
=> add-owners-for-ci

config/samples/rhtas_v1alpha1_securesign.yaml
=> Incorrect flag

ci/openshift/tas-keycloak-install.sh
@cooktheryan this script is to install keycloak resources in OpenShift CI clusters (I tested it locally, it works)
=> add script to install keycloak for openshift-ci

ci/openshift/tas-keycloak-install.sh
=> pin version for keycloak

config/samples/rhtas_v1alpha1_securesign.yaml, controllers/constants/images.go, controllers/rekor/utils/redis_deployment.go
Release candidate images for TP2
=> Rc1 images

.tekton/operator-1-0-gamma-pull-request.yaml, .tekton/operator-1-0-gamma-push.yaml, go.mod
=> adding prefetch hermetic and source builds to operator

config/rbac/auth_proxy_role_binding.yaml, config/rbac/leader_election_role.yaml, config/rbac/role.yaml, controllers/securesign_controller.go
Err `cannot create resource "events" in API group "" in the namespace`
=> Rbac error currently when following the operator log there are permissions issues

e2e/support/tas/ctlog.go
Reverts securesign/secure-sign-operator#91
=> Revert "trying to debug"

controllers/constants/images.go
=> redis-image-change

controllers/constants/images.go
=>  redis from main

controllers/constants/images.go
=> release image for redis

Makefile, bundle/manifests/operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, controllers/constants/images.go
=> switching references to RHTAP coordinates for operator image

e2e/cli_server_test.go
Fix IT test after the `ec` cli removal
=> Fix IT test after the ec removal

bundle.Dockerfile, bundle/manifests/catalog.yaml, bundle/manifests/devfile.yaml, bundle/metadata/annotations.yaml
These were added according to the docs ([Operator infrastructure feature test](https://docs.engineering.redhat.com/display/CVP/Operator+Verification+Pipeline+Documentation#operator-infrastructure-feature-test)) shared by Konflux team.
/cc @cooktheryan 
/cc @lance
=> adding annotations to csv for Operator infrastructure feature test

main.go
Reverts securesign/secure-sign-operator#97
/cc @lance
=> Revert "Remove ec CLI"

controllers/constants/images.go
These are the current "Snapshots", these are likely to change depending on merges over the next day or so!
=> Updating Images

controllers/constants/images.go
Works in main needing to bring into release
=> Update image to ensure we can reboot

fbc/v4.13/catalog/rhtas-operator/catalog.json
/cc @lance @JasonPowr @tommyd450
=> updating the catalog.json with the most recent build coordinates

fbc/v4.13/catalog/rhtas-operator/catalog.json, fbc/v4.13/graph.yaml
=> using rhtap refs and catalog re-generation

fbc/v4.13/catalog/rhtas-operator/catalog.json, fbc/v4.13/graph.yaml
=> bumping rhtap built bundle image for FBC image build

fbc/v4.13/release-plans/tech-preview-gamma-release.yaml
/cc @tommyd450 @lance @cooktheryan
=> Gamma release FBC 4.13 release plan

release-plans/ReleasePlan.yaml
=> release plan for gamma

Makefile, bundle.Dockerfile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manager/kustomization.yaml
=> swapping to tag based builds of bundle

bundle.Dockerfile
=> adding labels for EC passing

.tekton/operator-1-0-gamma-pull-request.yaml, .tekton/operator-1-0-gamma-push.yaml, .tekton/sigstore-operator-bundle-pull-request.yaml, .tekton/sigstore-operator-bundle-push.yaml, Dockerfile, bundle.Dockerfile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, fbc/v4.11/catalog/rhtas-operator/catalog.json, fbc/v4.12/catalog/rhtas-operator/catalog.json, fbc/v4.13/catalog/rhtas-operator/catalog.json, fbc/v4.14/catalog/rhtas-operator/catalog.json, fbc/v4.15/catalog/rhtas-operator/catalog.json, fbc/v4.16/catalog/rhtas-operator/catalog.json, go.mod
Take 2 inshallah
/cc @cooktheryan 
/cc @lance
=> updating pipelines for EC + Dockerfile according to tests

fbc/fbc-preflight-testing-steps
relates to: https://redhat-internal.slack.com/archives/C05M2GGKU7Q/p1708463359932889?thread_ts=1708460722.800729&cid=C05M2GGKU7Q
=> add preflight testing steps

api/v1alpha1/trillian_types.go, config/crd/bases/rhtas.redhat.com_securesigns.yaml, config/crd/bases/rhtas.redhat.com_trillians.yaml, e2e/byodb_test.go, e2e/common_install_test.go, e2e/config_update_test.go, e2e/key_autodiscovery_test.go, e2e/provided_certs_test.go
=> modify the default value of database

ci/openshift/tas-keycloak-install.sh
I notice I have an error in the keycloak install script, and updating to checkout the main branch
=> fix tas keycloak install script

bundle/manifests/rhtas-operator.clusterserviceversion.yaml
Small pr to fix the EC failures in konflux
=> fix: Fix EC in Konflux

ci/openshift/sign-test.sh
Bringing the item creation into the shell script rather than pulling external
=> include yaml in file and dont curl

.github/workflows/main.yml, ci/openshift/sign-test.sh, e2e/byodb_test.go, e2e/common_install_test.go, e2e/config_update_test.go, e2e/key_autodiscovery_test.go, e2e/provided_certs_test.go, e2e/support/oidc.go
Based on changes to Keycloak we need to modify the test
=> replacing values to represent TAS

Makefile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, bundle/manifests/rhtas.redhat.com_ctlogs.yaml, bundle/manifests/rhtas.redhat.com_fulcios.yaml, bundle/manifests/rhtas.redhat.com_rekors.yaml, bundle/manifests/rhtas.redhat.com_securesigns.yaml, bundle/manifests/rhtas.redhat.com_trillians.yaml, bundle/manifests/rhtas.redhat.com_tufs.yaml
In order to generate the correct catalog.json, files I need a bundle with the correct version for GA this prjust runs make bundle with the correct version
=> run make bundle

.tekton/fbc-v4-13-pull-request.yaml, fbc/v4.13/catalog.Dockerfile, fbc/v4.13/licenses/license.txt, fbc/v4.14/catalog.Dockerfile, fbc/v4.14/licenses/license.txt
This pr adds an license to the operator and triggers FBC image builds
=> Add license to FBC images

fbc/v4.13/catalog/rhtas-operator/catalog.json, fbc/v4.13/graph.yaml, fbc/v4.14/catalog/rhtas-operator/catalog.json, fbc/v4.14/graph.yaml, fbc/v4.15/catalog/rhtas-operator/catalog.json, fbc/v4.15/graph.yaml
Pr to update the FBC images to the most recent snapshot of the operator
=> Update FBC images to recent snapshot

controllers/constants/images.go
Updating the images to the latest snapshots.
=> chore: Update to latest images 

controllers/constants/images.go
Updating images to the latest snapshots
=> GA: image updates

.github/workflows/trigger-konflux-build.yaml, .tekton/fbc-v4-13-pull-request.yaml, .tekton/fbc-v4-13-push.yaml, .tekton/fbc-v4-14-pull-request.yaml, .tekton/fbc-v4-14-push.yaml, .tekton/fbc-v4-15-pull-request.yaml, .tekton/fbc-v4-15-push.yaml, .tekton/rhtas-operator-bundle-pull-request.yaml, .tekton/rhtas-operator-bundle-push.yaml, .tekton/rhtas-operator-pull-request.yaml, .tekton/rhtas-operator-push.yaml
Adding this action: https://github.com/securesign/actions/blob/main/.github/workflows/trigger-konflux-build.yaml
=> add-trigger-action

fbc/v4.13/catalog.Dockerfile, fbc/v4.14/catalog.Dockerfile, fbc/v4.15/catalog.Dockerfile
Trying to generate new FBC images, doing this manually as I don't want to generate a new image for everything
=> generating new builds

Makefile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
=> run-make-bundle

bundle.Dockerfile
=> trigger bundle build

fbc/v4.15/catalog.Dockerfile
revert to 4.14 as the 4.15 has vulnerabiliies
=> revert to 4.14

fbc/v4.13/catalog.Dockerfile, fbc/v4.14/catalog.Dockerfile, fbc/v4.15/catalog.Dockerfile
=> trigger builds

Makefile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml
=> forgot to bump operator version in csv + makefile

Makefile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, fbc/v4.13/catalog/rhtas-operator/catalog.json, fbc/v4.13/graph.yaml, fbc/v4.14/catalog/rhtas-operator/catalog.json, fbc/v4.14/graph.yaml, fbc/v4.15/catalog/rhtas-operator/catalog.json, fbc/v4.15/graph.yaml
bundle: `registry.redhat.io/rhtas/rhtas-operator-bundle@sha256:cbf83c222d175515b62e70c06670aefec59c9e1aaa3ce214dd06a28f5edce601`
operator: `registry.redhat.io/rhtas/rhtas-rhel9-operator@sha256:0fe2389cae04a9028c9a6ac977a8561ac67cba1a086cf5beaa370ac0187dd3d0`
/cc @lance @osmman
=> update operator and bundle shas to match snapshot: operator-54fl9

api/v1alpha1/securesign_types.go, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, bundle/manifests/rhtas.redhat.com_securesigns.yaml, config/crd/bases/rhtas.redhat.com_securesigns.yaml, config/samples/rhtas_v1alpha1_securesign.yaml, controllers/ctlog/actions/handle_fulcio_root_test.go, controllers/securesign/actions/rbac.go, controllers/securesign/actions/segment_backup_cronjob.go, controllers/securesign/actions/segment_backup_job.go, controllers/securesign/securesign_controller.go
=> implementing analytics section for securesign

controllers/common/utils/kubernetes/deployment.go, controllers/ctlog/actions/handle_fulcio_root_test.go, controllers/ctlog/ctlog_controller_test.go, controllers/ctlog/ctlog_hot_update_test.go, controllers/fulcio/fulcio_controller_test.go, controllers/fulcio/fulcio_hot_update_test.go, controllers/rekor/rekor_controller_test.go, controllers/rekor/rekor_hot_update_test.go, controllers/trillian/trillian_controller_test.go, controllers/tuf/tuf_controller_test.go, controllers/tuf/tuf_hot_update_test.go
requested by https://github.com/securesign/secure-sign-operator/pull/304
=> Move to Deployment conditions

fbc/v4.13/catalog/rhtas-operator/catalog.json, fbc/v4.13/graph.yaml, fbc/v4.14/catalog/rhtas-operator/catalog.json, fbc/v4.14/graph.yaml, fbc/v4.15/catalog/rhtas-operator/catalog.json, fbc/v4.15/graph.yaml
CC: @Gregory-Pereira @osmman @omveda
=> disable-upgrade-path

fbc/v4.13/catalog/rhtas-operator/catalog.json, fbc/v4.13/graph.yaml, fbc/v4.14/catalog/rhtas-operator/catalog.json, fbc/v4.14/graph.yaml, fbc/v4.15/catalog/rhtas-operator/catalog.json, fbc/v4.15/graph.yaml
/cc @osmman @lance @JasonPowr @tommyd450
=> downgrade tp2 operator to alpha channel

bundle/manifests/rhtas-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml
=> fix: use-upstream-rbac-image

Makefile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, bundle/manifests/rhtas.redhat.com_ctlogs.yaml, bundle/manifests/rhtas.redhat.com_securesigns.yaml, bundle/manifests/rhtas.redhat.com_trillians.yaml, config/manager/kustomization.yaml
=> 1.0.1: Run make bundle

bundle.Dockerfile
Build failed on push need to trigger again
=> trigger-bundle-build

fbc/v4.13/catalog.Dockerfile, fbc/v4.14/catalog.Dockerfile, fbc/v4.15/catalog.Dockerfile
=> trigger-fbc-builds

e2e/cli_server_test.go
Relates to [SECURESIGN-737](https://issues.redhat.com/browse/SECURESIGN-737)
=> Enable ec clientserver e2e test

controllers/common/utils/flag_or_env.go, controllers/constants/images.go, main.go
Adds the ability to specify an image when deploying the operator can be done either by flag or env var
=> feat: Add image EnVar/Flags 

Makefile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Adds latest operator snapshot sha to bundle
=> chore(bundle): make bundle with new image

.tekton/fbc-v4-13-pull-request.yaml, .tekton/fbc-v4-13-push.yaml, .tekton/fbc-v4-14-pull-request.yaml, .tekton/fbc-v4-14-push.yaml, .tekton/fbc-v4-15-pull-request.yaml, .tekton/fbc-v4-15-push.yaml, .tekton/rhtas-operator-bundle-pull-request.yaml, .tekton/rhtas-operator-bundle-push.yaml, .tekton/rhtas-operator-pull-request.yaml, .tekton/rhtas-operator-push.yaml
Relates to https://redhat-internal.slack.com/archives/C05M2GGKU7Q/p1715707450761549
/cc @lance
=> adding dep params for depricated image check

controllers/common/utils/kubernetes/common.go
Fixes [SECURESIGN-1002](https://issues.redhat.com//browse/SECURESIGN-1002)
=> Use SecurityContextConstraints resource to identify OCP environment

.tekton/rhtas-operator-bundle-push.yaml, .tekton/rhtas-operator-push.yaml
following: https://konflux-ci.dev/docs/how-tos/configuring/component-nudges/
=> add nudge annotation

controllers/common/action/base_action.go, controllers/ctlog/actions/handle_keys.go, controllers/ctlog/actions/serverConfig.go, controllers/ctlog/ctlog_controller.go, controllers/ctlog/ctlog_controller_test.go, controllers/ctlog/ctlog_hot_update_test.go, controllers/ctlog/suite_test.go, controllers/fulcio/fulcio_controller_test.go, controllers/fulcio/fulcio_hot_update_test.go, controllers/fulcio/suite_test.go, controllers/rekor/rekor_controller_test.go, controllers/rekor/rekor_hot_update_test.go, controllers/rekor/suite_test.go, controllers/trillian/suite_test.go, controllers/trillian/trillian_controller_test.go, controllers/tuf/actions/generate_cert.go, controllers/tuf/suite_test.go, controllers/tuf/tuf_controller.go, controllers/tuf/tuf_controller_test.go, controllers/tuf/tuf_hot_update_test.go
A few minor fixes that should increase test stability.
=> Increase test stability

.github/workflows/main.yml, .github/workflows/upgrade.yml, controllers/constants/images.go
Based off of https://github.com/securesign/releases/pull/33/files#diff-337ca79c2cbf45dcec0673c4a6b5fc9fadbe286a1d9f2354dac6fc7d1da4c649
=> release-1.0-update-images

controllers/clidownload/component.go, controllers/common/utils/kubernetes/common.go, main.go
Fixes [SECURESIGN-1002](https://issues.redhat.com//browse/SECURESIGN-1002)
=> [SECURESIGN-1002] Move creation of cli server to manager startup cycle

internal/controller/common/utils/set_proxy.go, internal/controller/common/utils/set_proxy_test.go, internal/controller/ctlog/utils/ctlog_deployment.go, internal/controller/fulcio/utils/fulcio_deployment.go, internal/controller/rekor/utils/redis_deployment.go, internal/controller/rekor/utils/rekor_deployment.go, internal/controller/trillian/utils/trillian-deployment.go, internal/controller/tuf/utils/tuf_deployment.go
jira: https://issues.redhat.com/browse/SECURESIGN-1038
follow-up: https://github.com/securesign/secure-sign-operator/pull/466#issuecomment-2191664346
=> feat: pass proxy configuration to operands

internal/controller/securesign/actions/segment_backup_cronjob.go, internal/controller/securesign/actions/segment_backup_job.go
Inspects environment proxy variables and appends them to Operand environments making them proxy aware.
=> [SECURESIGN-1206] Making segment backup job proxy aware 

internal/controller/securesign/actions/segment_backup_job.go
Fixes panic error caused by incorrect number of parameters for error logger function
=> Fix incorrect number of parameters for SBJ error logging

api/v1alpha1/common.go, api/v1alpha1/fulcio_types.go, api/v1alpha1/fulcio_types_test.go, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, bundle/manifests/rhtas.redhat.com_fulcios.yaml, bundle/manifests/rhtas.redhat.com_securesigns.yaml, config/crd/bases/rhtas.redhat.com_fulcios.yaml, config/crd/bases/rhtas.redhat.com_securesigns.yaml, internal/controller/fulcio/utils/errors.go, internal/controller/fulcio/utils/fulcio_deployment.go, internal/controller/fulcio/utils/fulcio_deployment_test.go
resolves: [SECURESIGN-1198](https://issues.redhat.com//browse/SECURESIGN-1198)
=> feat: add prefix parameter into Fulcio's ctlog config

internal/controller/constants/images.go
=> chore: update rekor image

internal/controller/common/utils/kubernetes/deployment.go, internal/controller/ctlog/actions/initialize.go, internal/controller/ctlog/ctlog_controller_test.go, internal/controller/ctlog/ctlog_hot_update_test.go, internal/controller/fulcio/actions/initialize.go, internal/controller/fulcio/fulcio_controller_test.go, internal/controller/fulcio/fulcio_hot_update_test.go, internal/controller/rekor/actions/redis/initialize.go, internal/controller/rekor/actions/server/generate_signer.go, internal/controller/rekor/actions/server/initialize.go, internal/controller/rekor/actions/server/resolve_pub_key.go, internal/controller/rekor/actions/ui/initialize.go, internal/controller/rekor/rekor_controller_test.go, internal/controller/rekor/rekor_hot_update_test.go, internal/controller/trillian/actions/db/initialize.go, internal/controller/trillian/actions/logserver/initialize.go, internal/controller/trillian/actions/logsigner/initialize.go, internal/controller/trillian/trillian_controller_test.go, internal/controller/tsa/actions/initialize.go, internal/controller/tsa/timestampauthority_controller_test.go, internal/controller/tsa/tsa_hot_update_test.go, internal/controller/tuf/actions/initialize.go, internal/controller/tuf/tuf_controller_test.go, internal/controller/tuf/tuf_hot_update_test.go, internal/testing/kubernetes/deployment.go
=> fix: check observed, available and new replica set statuses to decide if deployment is ready

internal/controller/constants/images.go, internal/controller/securesign/actions/segment_backup_cronjob.go, internal/controller/securesign/actions/segment_backup_job.go
This is part two of a two part fix, opening as a draft for know until I can get a image for sbj that includes my fixes :)
=> SECURESIGN-1221 | SBJ Not reaching segment endpoint

.github/workflows/main.yml, internal/controller/tsa/utils/tsa_cert_chain.go, test/e2e/support/tas/tsa/tsa.go
Bug fix for cosign not recognising leaf cert
=> fix: Make sure cosign recognises leaf cert

internal/controller/trillian/actions/db/initialize.go, internal/controller/trillian/actions/initialize.go, internal/controller/trillian/actions/logserver/initialize.go, internal/controller/trillian/actions/logsigner/initialize.go, internal/controller/trillian/trillian_controller.go, test/e2e/upgrade_test.go
related to [SECURESIGN-1343](https://issues.redhat.com//browse/SECURESIGN-1343)
=> fix(trillian): run initialize check when deployment changed

internal/controller/ctlog/actions/handle_keys.go
related to [SECURESIGN-662](https://issues.redhat.com/browse/SECURESIGN-662)
=> fix(ctlog): fix handle key action condition for private password ref

docs/ctlog-key-rotation.md
releated to [SECURESIGN-662](https://issues.redhat.com//browse/SECURESIGN-662)
=> doc(ctlog): patch password reference and fix ctlog pod label

docs/rekor-sharding.md
related to [SECURESIGN-568](https://issues.redhat.com//browse/SECURESIGN-568)
=> doc(rekor): modify verification steps for sharding step

api/v1alpha1/fulcio_types.go, internal/controller/constants/images.go, internal/controller/fulcio/actions/servrConfig.go, internal/controller/fulcio/actions/servrConfig_test.go, internal/controller/fulcio/actions/testdata/config.json, internal/controller/fulcio/actions/testdata/config.yaml, test/e2e/update/fulcio_test.go
fulcio configuration was updated in the latest versions (config.json -> config.yaml):
https://github.com/sigstore/fulcio/blob/main/pkg/config/config.go#L53-L119
=> update images, update fulcio config format

internal/controller/constants/images.go
related to [SECURESIGN-1395](https://issues.redhat.com//browse/SECURESIGN-1395)
=> fix: tuffer image name

api/v1alpha1/rekor_types.go, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, bundle/manifests/rhtas.redhat.com_rekors.yaml, bundle/manifests/rhtas.redhat.com_securesigns.yaml, config/crd/bases/rhtas.redhat.com_rekors.yaml, config/crd/bases/rhtas.redhat.com_securesigns.yaml
=> doc(rekor): document Rekor's signer options for KMS

internal/controller/common/utils/kubernetes/config_map.go, internal/controller/common/utils/kubernetes/config_map_test.go, internal/controller/fulcio/actions/server_config.go, internal/controller/fulcio/actions/server_config_test.go, internal/controller/rekor/actions/server/sharding_config.go, internal/controller/rekor/actions/server/sharding_config_test.go, internal/controller/tsa/actions/ntpMonitoring.go
- migrate ConfigMap to new ensure
- eliminate CreateConfigMap to avoid usage in source-code
=> [SECURESIGN-1393] migrate ConfigMap

internal/controller/constants/images.go
I updated the latest images to match the ones in my release PR for 1.1.1
=> Update latest images

Makefile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
| registry.redhat.io/rhtas/rhtas-rhel9-operator | 262a612 | 6f9c4e8 |
---
=> :robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image

internal/controller/fulcio/actions/deployment.go
fixes issue [SECURESIGN-1989](https://issues.redhat.com//browse/SECURESIGN-1989)
=> fix: mount kubernetes api server certificate to /var/run/fulcio/ca.crt

internal/controller/fulcio/utils/fulcio_deployment.go
fixes issue [SECURESIGN-1989](https://issues.redhat.com//browse/SECURESIGN-1989)
=> [release-1.2] fix: mount kubernetes api server certificate to /var/run/fulcio/ca.crt

.tekton/rhtas-operator-bundle-pull-request.yaml, .tekton/rhtas-operator-bundle-push.yaml, bundle.Dockerfile
change component and name labels values to rhtas-operator-bundle
Reference:
- https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md
- https://github.com/konflux-ci/olm-operator-konflux-sample/blob/main/Containerfile.gatekeeper-operator-bundle
=> [release-1.2] fix: build bundle image from scratch

Makefile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, bundle/manifests/rhtas-related-images_v1_configmap.yaml, config/manager/kustomization.yaml, config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
| registry.redhat.io/rhtas/rhtas-rhel9-operator | 82fd584 | 0808a2d |
---
=> :robot: [RHTAS-build-bot] [release-1.2] Update Operator Bundle Controller Image

.tekton/rhtas-operator-bundle-pull-request.yaml, .tekton/rhtas-operator-bundle-push.yaml
Adding two tasks that are causing EC to fail
=> Update build pipelines

Dockerfile.rhtas-operator.rh
Manually triggering a build of release1-2  as the last build failed EC and would fail to release. Also rerun doesnt seem to be working
=> Manually triggering build

internal/controller/constants/images.go
| registry.redhat.io/rhtas/rekor-search-ui-rhel9 | `254842b` | `571c48e` |
| registry.redhat.io/rhtas/fulcio-rhel9 | `20beb19` | `329a0da` |
---
=> :robot: [RHTAS-build-bot] [release-1.1] Update Component images

Makefile, bundle/manifests/rhtas-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
| registry.redhat.io/rhtas/rhtas-rhel9-operator | 926036d | e52d07e |
---
=> :robot: [RHTAS-build-bot] [release-1.1] Update Operator Bundle Controller Image

internal/controller/common/utils/kubernetes/ensure/deployment/deployment.go, internal/controller/common/utils/kubernetes/ensure/set_proxy.go, internal/controller/common/utils/kubernetes/ensure/set_proxy_test.go, internal/controller/fulcio/actions/deployment.go
Fixes [SECURESIGN-2150](https://issues.redhat.com//browse/SECURESIGN-2150)
=> fix: add Fulcio's legacy unix socket into no_proxy env vars

.github/workflows/main.yml, Dockerfile.rhtas-operator.rh, Makefile, bundle.Dockerfile, config/manifests/bases/rhtas-operator.clusterserviceversion.yaml
Other
___
- Update version from 1.3.0 to 1.4.0 across configuration files
- Update OLM channel to rhtas-operator.v1.4.0
- Update stable channel to stable-v1.4
___
```mermaid
flowchart LR
A["Version 1.3.0"] --> B["Version 1.4.0"]
C["stable-v1.3 channel"] --> D["stable-v1.4 channel"]
E["rhtas-operator.v1.3.0"] --> F["rhtas-operator.v1.4.0"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>main.yml</strong><dd><code>Update OLM channel version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> chore: initialise 1.4.0 release
