.gitignore
tas-env-generate.sh

Adds script to generate the env vars file, similar to tas-easy-install.sh, but without the KEYCLOAK assumption
User must provide OIDC_ISSUER_URL like so:
```
./tas-env-generate.sh -o https://your-oidc-issuer-url
```
User can provide the flag `-b` to provide BASE_HOSTNAME, but script will try to obtain if from connected cluster if not provided.

add script to generate env vars

---

controllers/common/utils/kubernetes/ingress.go

Problem was occurring where certificate was valid for *.apps but would have issues with namespace.*.apps with the certificate not being valid
Successful initialization
```
cosign initialize --mirror=https://tuf-test.apps.rosa.t6yip-us2iv-48p.6hh1.p3.openshiftapps.com --root=https://tuf-test.apps.rosa.t6yip-us2iv-48p.6hh1.p3.openshiftapps.com/root.json
Root status:
{
"local": "/home/rcook/.sigstore/root",
"remote": "https://tuf-test.apps.rosa.t6yip-us2iv-48p.6hh1.p3.openshiftapps.com",
"metadata": {
"root.json": {
"version": 1,
"len": 2178,
"expiration": "30 Jul 24 19:12 UTC",
"error": ""
},
"snapshot.json": {
"version": 1,
"len": 618,
"expiration": "30 Jul 24 19:12 UTC",
"error": ""
},
"targets.json": {
"version": 1,
"len": 1372,
"expiration": "30 Jul 24 19:12 UTC",
"error": ""
}, …
```

ingress change due to ocp cert issue

---

controllers/constants/images.go

Image needs to be tested by rebooting nodes after DB has been running. If passes we should bring the registry.redhat.io image into the operator

trillian-db

---

bundle/manifests/rhtas-operator.clusterserviceversion.yaml
config/manifests/bases/rhtas-operator.clusterserviceversion.yaml

updating csv to v0.0.2

---

fbc/v4.11/catalog/rhtas-operator/catalog.json
fbc/v4.11/graph.yaml
fbc/v4.12/catalog/rhtas-operator/catalog.json
fbc/v4.12/graph.yaml
fbc/v4.13/catalog/rhtas-operator/catalog.json
fbc/v4.13/graph.yaml
fbc/v4.14/catalog/rhtas-operator/catalog.json
fbc/v4.14/graph.yaml
fbc/v4.15/catalog/rhtas-operator/catalog.json
fbc/v4.15/graph.yaml
fbc/v4.16/catalog/rhtas-operator/catalog.json
fbc/v4.16/graph.yaml

Can confirm all SHAs are correct here, we just need to discover why our `redis` and `rekor-search-ui-rhel9` are not built
/cc @osmman @petrpinkas @ppecka @lance 
Relates to: https://redhat-internal.slack.com/archives/C05M2GGKU7Q/p1707450833732149?thread_ts=1707449931.383969&cid=C05M2GGKU7Q

updating fbcs to 0.0.2

---

Dockerfile
bundle.Dockerfile

If I am right marking EC as optional will allow us to promote images for testing, because seemingly what has happend is the EC is running against builds from friday even though there have been extra builds and succeessful pushes since then.

Triggering builds to promote images.

---

fbc/v4.11/catalog/rhtas-operator/catalog.json
fbc/v4.12/catalog/rhtas-operator/catalog.json
fbc/v4.13/catalog/rhtas-operator/catalog.json
fbc/v4.14/catalog/rhtas-operator/catalog.json
fbc/v4.15/catalog/rhtas-operator/catalog.json
fbc/v4.16/catalog/rhtas-operator/catalog.json

Updating the FBC with current snapshots, this will also might fix that error with v0.0.1 appearing although I am not sure.

Updating FBC catalogues with current operator snapshot images

---

ci/openshift/job.yaml

This job is needed for OpenShift CI to be able to push an image before doing cosign

job for openshift CI

---

.github/workflows/main.yml
api/v1alpha1/common.go
api/v1alpha1/rekor_types.go
api/v1alpha1/trillian_types.go
config/crd/bases/rhtas.redhat.com_rekors.yaml
config/crd/bases/rhtas.redhat.com_securesigns.yaml
config/crd/bases/rhtas.redhat.com_trillians.yaml
controllers/trillian/actions/db/pvc.go

The retain functionality was not properly working after the last merge

fix of retain functionality

---

controllers/constants/images.go
main.go

This pr makes the necessary changes to the client sever, after the split one contains cosign and gitsign the other contains rekor-cli and ec

Split Client server into two images

---

Makefile
bundle/manifests/rhtas-operator.clusterserviceversion.yaml
bundle/manifests/rhtas.redhat.com_ctlogs.yaml
bundle/manifests/rhtas.redhat.com_fulcios.yaml
bundle/manifests/rhtas.redhat.com_securesigns.yaml
config/manager/kustomization.yaml

Trying to generate a new build of the FBC images, need to run make bundle first with our current snapshotted image of the operator to generate a new bundle image

Run make bundle

---

api/v1alpha1/fulcio_types.go
api/v1alpha1/fulcio_types_test.go
config/crd/bases/rhtas.redhat.com_fulcios.yaml
config/crd/bases/rhtas.redhat.com_securesigns.yaml
controllers/ctlog/actions/handle_fulcio_root.go
controllers/ctlog/actions/handle_keys.go
controllers/fulcio/actions/generate_cert.go
controllers/fulcio/utils/fulcio_secrets.go
controllers/rekor/actions/server/generate_signer.go
e2e/provided_certs_test.go

Fixing requirements on generated Fulcio root certificate by operator and use ECDSA P-384 (secp384r1) for generated keys.
https://github.com/sigstore/fulcio/blob/main/docs/certificate-specification.md

Fix generated Fulcio root certificate requirements

---

.tekton/fbc-v4-13-pull-request.yaml
.tekton/fbc-v4-13-push.yaml
.tekton/fbc-v4-14-pull-request.yaml
.tekton/fbc-v4-14-push.yaml
.tekton/fbc-v4-15-pull-request.yaml
.tekton/fbc-v4-15-push.yaml
.tekton/rhtas-operator-bundle-pull-request.yaml
.tekton/rhtas-operator-bundle-push.yaml
.tekton/rhtas-operator-pull-request.yaml
.tekton/rhtas-operator-push.yaml

This pr makes changes to the tekton cel expressions, this makes sure that the fbc images, the bundle and the operator can build independently. 
"I think having the operator and the bundle in the same application in Konflux causes some issues.When we generate an image for the operator-controller in Konflux, we then go back and update the bundle. When we update the bundle it generates a new image for the operator-controller, this means that when we release we use a snapshot that has an up to date controller image, but the image being used in the bundle isn’t the one in the snapshot, it's the one generated previously. If we were to separate them into different applications they could be built independently, wdyt? Or probably a better solution would be to add the cel expression to the …

Update Konflux CEL expressions 

---

controllers/constants/images.go
fbc/v4.13/catalog/rhtas-operator/catalog.json
fbc/v4.14/catalog/rhtas-operator/catalog.json
fbc/v4.15/catalog/rhtas-operator/catalog.json

This commit is an attempt to use ose-tools instead of a custom netcat providing the same capabilities. I have run unit tests but not e2e.

deps(netcat): replace custom netcat with ose-tools

---

api/v1alpha1/fulcio_types.go
api/v1alpha1/fulcio_types_test.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/rhtas-operator.clusterserviceversion.yaml
bundle/manifests/rhtas.redhat.com_ctlogs.yaml
bundle/manifests/rhtas.redhat.com_fulcios.yaml
bundle/manifests/rhtas.redhat.com_rekors.yaml
bundle/manifests/rhtas.redhat.com_securesigns.yaml
bundle/manifests/rhtas.redhat.com_trillians.yaml
bundle/manifests/rhtas.redhat.com_tufs.yaml
ci/openshift/sign-test.sh
config/crd/bases/rhtas.redhat.com_fulcios.yaml
config/crd/bases/rhtas.redhat.com_securesigns.yaml
config/samples/rhtas_v1alpha1_fulcio.yaml
config/samples/rhtas_v1alpha1_securesign.yaml
controllers/fulcio/actions/servrConfig.go
controllers/fulcio/fulcio_controller_test.go
controllers/fulcio/fulcio_hot_update_test.go
e2e/byodb_test.go
e2e/common_install_test.go
e2e/config_update_test.go
e2e/key_autodiscovery_test.go
e2e/provided_certs_test.go

This pr fixes the issue laid out in this jira https://issues.redhat.com/browse/SECURESIGN-589, The main issues was with how the issuer info was stored in the api.

SECURESIGN-589 | Fulcio OIDC issuers configuration does not show in Web Form

---

controllers/securesign/actions/segment_backup_cronjob.go
controllers/securesign/actions/segment_backup_job.go

For some reason the cluster wasn't applying the "get" to the configmaps resource properly separating them seems to work, I was also seeing errors related to patch thats why I added it

fix-sbj-cluster-role

---

bundle/manifests/rhtas-operator.clusterserviceversion.yaml
bundle/manifests/rhtas.redhat.com_ctlogs.yaml
bundle/manifests/rhtas.redhat.com_securesigns.yaml
bundle/manifests/rhtas.redhat.com_trillians.yaml
config/manifests/bases/rhtas-operator.clusterserviceversion.yaml

This pr makes the changes necessary to display missing metadata in the operator marketplace 
Jira: https://issues.redhat.com/browse/SECURESIGN-801
Here is an CatalogSource yaml definition you can use if you want to test, with my FBC image
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: rhtas-operator-japower
namespace: openshift-marketplace
spec:
sourceType: grpc
grpcPodConfig:
securityContextConfig: legacy
publisher: Red Hat
image: quay.io/japower/4.15_test@sha256:1cee7ca01822206d8aa154614fde8119a2b8769f63a6a21047987b7f8e124c6c
displayName: TAS Operator
```

fix: add-missing-metadata

---

docs/Backup.md
docs/OADP-Install.md
docs/Restore.md
docs/samples/Backup_Sample.yaml
docs/samples/CSI_sample.yaml
docs/samples/DataProtectionApplication_Sample.yaml
docs/samples/Restore_Sample.yaml
docs/samples/credentials_aws_sample.yaml

First draft of these if someone has the cycles to give this a test please ping me here or on slack with questions.

[Securesign 297] Backup and Restore Docs

---

controllers/common/password.go

Snyk.io was complaining about the use of ` math.rand.Intn` to generate the password and recommend we switch to crypto/rand.
Ref: https://app.snyk.io/org/application-services-red-hat-trusted-artifact-signer/project/7226cc76-b503-4925-b193-c8cc5459f3de

fix: fix-snyk-vul

---

bundle/manifests/rhtas-operator.clusterserviceversion.yaml
bundle/manifests/rhtas.redhat.com_fulcios.yaml
bundle/manifests/rhtas.redhat.com_securesigns.yaml
config/manager/manager.yaml

Fixes [SECURESIGN-833](https://issues.redhat.com//browse/SECURESIGN-833)

Rises a memory limit to 256Mi on manager's container

---

api/v1alpha1/common.go
api/v1alpha1/fulcio_types_test.go
api/v1alpha1/securesign_types.go
bundle/manifests/rhtas-operator.clusterserviceversion.yaml
bundle/manifests/rhtas.redhat.com_fulcios.yaml
bundle/manifests/rhtas.redhat.com_rekors.yaml
bundle/manifests/rhtas.redhat.com_securesigns.yaml
config/crd/bases/rhtas.redhat.com_ctlogs.yaml
config/crd/bases/rhtas.redhat.com_fulcios.yaml
config/crd/bases/rhtas.redhat.com_rekors.yaml
config/crd/bases/rhtas.redhat.com_securesigns.yaml
config/crd/bases/rhtas.redhat.com_trillians.yaml
config/rbac/role.yaml
config/samples/rhtas_v1alpha1_securesign.yaml
controllers/securesign/actions/rbac.go
controllers/securesign/actions/segment_backup_cronjob.go
controllers/securesign/actions/segment_backup_job.go
controllers/securesign/securesign_controller.go
e2e/byodb_test.go
e2e/common_install_test.go
e2e/config_update_test.go
e2e/key_autodiscovery_test.go
e2e/provided_certs_test.go

fix: Use roles instead of cluster roles for SBJ

---

controllers/common/create_tree.go
controllers/ctlog/ctlog_hot_update_test.go

This pr is a WIP as I believe this is the solution and I  also need to update tests still.
Where the error itself originates is within the trillian repo [here](https://github.com/securesign/trillian/blob/303a8bdbe307e5dbc703221cc782395ee72ee986/client/admin.go#L49) there isnt anything wrong on the trillian end but rather ours, that snippet of code will run forever without a specified deadline.
I have added some deadline flags to ctlog and rekor with a default set for 5 minutes.

[Securesign 835] | Create Tree Error Looping indefinetley.

---

bundle/manifests/rhtas-operator.clusterserviceversion.yaml
config/manifests/bases/rhtas-operator.clusterserviceversion.yaml

Increase operator maturity level - level 2 is supported (see https://sdk.operatorframework.io/docs/overview/operator-capabilities/#level-2---seamless-upgrades)

Upgrade operator maturity level

---

api/v1alpha1/fulcio_types.go
api/v1alpha1/fulcio_types_test.go
bundle/manifests/rhtas.redhat.com_fulcios.yaml
bundle/manifests/rhtas.redhat.com_securesigns.yaml
config/crd/bases/rhtas.redhat.com_fulcios.yaml
config/crd/bases/rhtas.redhat.com_securesigns.yaml
controllers/common/utils/kubernetes/common.go
controllers/common/utils/kubernetes/ingress.go
controllers/fulcio/actions/generate_cert.go
controllers/fulcio/utils/fulcio_secrets.go

Jira: https://issues.redhat.com/browse/SECURESIGN-851
If commonName is empty in the CRD definition, One will be calculated based on the ns and name of service

fix: Set the common name of the Fulcio cert automatically 

---

controllers/ctlog/actions/handle_keys.go

Solves [SECURESIGN-675](https://issues.redhat.com//browse/SECURESIGN-675)

Handle error when ctlog unable to generate public key

---

controllers/annotations/annotations.go
controllers/common/action/base_action.go
controllers/ctlog/ctlog_controller.go
controllers/fulcio/fulcio_controller.go
controllers/rekor/rekor_controller.go
controllers/securesign/securesign_controller.go
controllers/trillian/trillian_controller.go
controllers/tuf/tuf_controller.go
go.mod
go.sum

Add a new `rhtas.redhat.com/pause-reconciliation` annotation to pause resource reconciliation. Annotation can be used on any Securesign's custom resource and resources which are owned by them like Deploymen, Service, Ingress
Example custom resource with a paused reconciliation condition
```
kind: Tuf
metadata:
annotations:
rhtas.redhat.com/pause-reconciliation: "true"
```

Add annotation to pause resource reconciliation

---

api/v1alpha1/rekor_types_test.go
api/v1alpha1/trillian_types_test.go
docs/custom-ca.md
internal/controller/annotations/annotations.go
internal/controller/annotations/annotations_test.go
internal/controller/common/utils/set_trusted_ca.go
internal/controller/common/utils/set_trusted_ca_test.go
internal/controller/ctlog/actions/deployment.go
internal/controller/fulcio/utils/fulcio_deployment.go
internal/controller/fulcio/utils/fulcio_deployment_test.go
internal/controller/rekor/actions/server/deployment.go
internal/controller/securesign/actions/ensure_ctlog.go
internal/controller/securesign/actions/ensure_fulcio.go
internal/controller/securesign/actions/ensure_rekor.go
internal/controller/securesign/actions/ensure_trillian.go
internal/controller/securesign/actions/ensure_tuf.go
internal/controller/securesign/actions/segment_backup_cronjob.go
internal/controller/securesign/actions/segment_backup_job.go
internal/controller/trillian/actions/logserver/deployment.go
internal/controller/trillian/actions/logsigner/deployment.go

related to https://issues.redhat.com/browse/SECURESIGN-703 and https://issues.redhat.com/browse/SECURESIGN-1037

Inject CA trust bundle into managed containers and set SSL_CERT_DIR

---

api/v1alpha1/rekor_types.go
cmd/main.go
config/crd/bases/rhtas.redhat.com_rekors.yaml
config/crd/bases/rhtas.redhat.com_securesigns.yaml
internal/clidownload/component.go
internal/controller/rekor/actions/ui/ingress.go

I messed up the commit tree in https://github.com/securesign/secure-sign-operator/pull/414, so reopening here

feat: provide host name option for CLI and search ui

---

internal/controller/ctlog/ctlog_controller.go
internal/controller/ctlog/ctlog_hot_update_test.go
internal/controller/fulcio/fulcio_controller.go
internal/controller/rekor/rekor_controller.go
internal/controller/rekor/rekor_hot_update_test.go
internal/controller/securesign/securesign_controller.go
internal/controller/trillian/trillian_controller.go
internal/controller/tuf/tuf_controller.go
test/e2e/support/archive.go
test/e2e/support/common.go

This pull request introduces a check in the reconcile function to determine if the namespace is marked for deletion. If the namespace is in the process of being terminated, the reconciliation will cease. This enhancement prevents the operator from attempting to create or update objects within a terminating namespace, thereby avoiding error messages such as:
```
unable to create new content in namespace test-b22323db-f1c2-4d5b-b4ba-f5bdd4aa257a because it is being terminated
```

Namespace deletion check in Reconcile function

---

internal/controller/securesign/securesign_controller.go

It fixes bug which prevent to delete namespace because of existing finalizer on Securesign resource. Problem has been solved by moving check on namespace after finalizer has been handled.

Remove finalizer before interupting reconcile function

---

docs/rekor-key-rotation.md

Depends on: https://github.com/securesign/secure-sign-operator/pull/512

doc: Rotation the signer key for Rekor service

---

.tekton/rhtas-operator-bundle-pull-request.yaml
.tekton/rhtas-operator-bundle-push.yaml
.tekton/rhtas-operator-pull-request.yaml
.tekton/rhtas-operator-push.yaml

Konflux does not have a way of introducing new tasks into our build pipelines automatically. Instead, we need to do these things manually. The image preflight checks are new as of a couple of months ago, and are now being added to all new components as they are onboarded. This commit brings the operator pipelines up to date with that addition. Apparently, it also removes a whitespace from the cel expression.

chore: add preflight checks to pipelines

---

cmd/main.go
internal/metrics/metrics.go

**Description:**
Enabling RecoverPanic functionality on controllers and adds a new PanicHandler which will record event into `controller_runtime_reconcile_panics_total` metric.

SECURESIGN-1275: Enable RecoverPanic on controllers

---

.github/workflows/main.yml

actions/cache@v3 has been removed because actions/setup-go@v5 has already activated and preconfigured cache by default.

chore: update checkout and setup-go actions

---

test/e2e/byodb_test.go
test/e2e/common_install_test.go
test/e2e/config_update_test.go
test/e2e/key_autodiscovery_test.go
test/e2e/provided_certs_test.go
test/e2e/support/tas/tsa.go
test/e2e/upgrade_test.go

Small fix the upgrade test, adds a retry to the GetTSACertificateChain() func

chore: patch-tsa-upgrade-test

---

.github/workflows/main.yml
bundle/manifests/rhtas-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/rhtas-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
bundle/manifests/rhtas-operator-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/rhtas-operator.clusterserviceversion.yaml
config/default/kustomization.yaml
config/default/manager_metrics_patch.yaml
config/manager/kustomization.yaml
config/manager/metrics_service.yaml
config/prometheus/monitor.yaml

To test this, you just need to build and deploy the operator, you should see a new target being created under `Observe -> Targets` called `rhtas-operator-controller-manager-metrics-monitor`, you should then be able to query the metrics of the operator.

SECURESIGN-842 | Operator's metrics are not consumed by OCP monitor

---

docs/tsa-key-rotation.md

Adds a markdown document detailing the rotation of the signer keys and certificate chain for the Timestamp authority service.

SECURESIGN-1203 | Add TSA key rotation doc

---

internal/controller/common/utils/kubernetes/deployment.go
internal/controller/rekor/actions/server/generate_signer.go
internal/controller/rekor/actions/server/generate_signer_test.go
test/e2e/config_update_test.go

It fixes:
1. create new immutable secret only for generated signer key
2. identify changes in spec.signer.kms and apply them
3. ignore privateKey if kms is not empty 
4. simplify generation function signer key, because it will newer generate key by password

fix(rekor): create new secret only for generated signer key

---

docs/fulcio-key-rotation.md
internal/controller/fulcio/actions/generate_cert.go

Adds a doc describing the steps needed to rotate the fulcio keys, replaces deleting the key and cert if a new ones is generated with simply removing the label

SECURESIGN-1200 | Fulcio key rotation

---

internal/controller/securesign/actions/constants.go
internal/controller/securesign/actions/initialize_status.go
internal/controller/securesign/actions/segment_backup_job.go

Small bug fix, I noticed sometimes SBJ would run twice on re-installation, as in two jobs would run at the same time, this negates the issue

fix: Make sure SBJ installation runs only once

---

docs/rekor-sharding.md

related to [SECURESIGN-568](https://issues.redhat.com//browse/SECURESIGN-568)

doc(rekor): add rekor_server option for rekor-cli commands

---

docs/ctlog-key-rotation.md

related to [SECURESIGN-662](https://issues.redhat.com//browse/SECURESIGN-662)

doc(ctlog): update treeID in key rotation patch

---

Makefile
bundle/manifests/rhtas-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/rhtas-operator.clusterserviceversion.yaml

due to the merge of https://github.com/securesign/secure-sign-operator/commit/08f32a4133c814364bace95778b01a5a09a6cc28
Operator image has changed.

RC2: make bundle - 2nd attempt 

---

internal/controller/ctlog/actions/deployment.go
internal/controller/ctlog/actions/handle_fulcio_root.go
internal/controller/ctlog/actions/handle_keys.go
internal/controller/ctlog/actions/initialize.go
internal/controller/ctlog/actions/monitoring.go
internal/controller/ctlog/actions/rbac.go
internal/controller/ctlog/actions/resolve_tree.go
internal/controller/ctlog/actions/server_config.go
internal/controller/ctlog/actions/server_config_test.go
internal/controller/ctlog/actions/service.go

related to [SECURESIGN-1227](https://issues.redhat.com//browse/SECURESIGN-1227)
CT log server config has not been updated when spec has changed. Because that configuration depends mostly on all fields in spec I solved that problem by comparing latest observed generation for Ready phase. `serverConfig` action will be executed on Ready phase when ObservedGeneration is different than Generation of resource.

fix: recreate ctlog config when spec has changed

---

internal/controller/trillian/actions/db/handle_secret.go
internal/controller/trillian/actions/db/handle_secret_test.go
internal/controller/trillian/actions/db/pvc.go
internal/controller/trillian/trillian_controller.go
internal/controller/trillian/utils/constants.go
internal/controller/trillian/utils/server-deployment.go
internal/controller/trillian/utils/signer-deployment.go
internal/controller/trillian/utils/trillian-db.go

fixes [SECURESIGN-1461](https://issues.redhat.com//browse/SECURESIGN-1461)
depends on https://github.com/securesign/secure-sign-operator/pull/673

SECURESIGN-1461: check if Trillian's secret with db connection already exists

---

internal/controller/ctlog/actions/constants.go
internal/controller/ctlog/actions/handle_fulcio_root.go
internal/controller/ctlog/actions/handle_fulcio_root_test.go
internal/controller/ctlog/actions/handle_keys.go
internal/controller/ctlog/actions/resolve_tree.go
internal/controller/ctlog/actions/server_config.go
internal/controller/ctlog/actions/server_config_test.go
internal/controller/ctlog/ctlog_controller.go

**Handling of Deleted Generated Secrets:**
In cases where generated secrets were being deleted due to duplicate events during the operator's reconciliation process, I have adjusted order of execution. Now, any secrets that have the expected resource labels will be removed after successful creation of new one.
**ServerConfig Invalidation Mechanism:**
I have modified the mechanism that invalidates the current server configuration in response to external actions, such as the creation of a Trillian tree, issuance of Fulcio certificates, or the generation of signer keys. When any of these external actions result in a change of data, the ServerConfigAvaliable status is now correctly set to `false`. This triggers the necessary reconciliation to maintain the correct state of the server …

fix(ctlog): cleanup only linked server configs

---

internal/controller/rekor/actions/server/resolve_pub_key.go
internal/controller/rekor/rekor_controller_test.go

When running the operator locally against an openshift cluster the Rekor pub key fails to resolve, this fixes that

fix: Resolving rekor pub key locally against openshift

---

test/e2e/benchmark/install_test.go
test/e2e/support/condition/condition.go
test/e2e/support/oidc.go
test/e2e/support/tas/ctlog/ctlog.go
test/e2e/support/tas/fulcio/fulcio.go
test/e2e/support/tas/rekor/rekor.go
test/e2e/support/tas/rekor/search_ui.go
test/e2e/support/tas/securesign/securesign.go
test/e2e/support/tas/trillian/trillian.go
test/e2e/support/tas/tsa/tsa.go
test/e2e/support/tas/tuf/tuf.go

The scenario will install default TAS, sign and verify one image and delete TAS.
Example of command to install TAS 10x:
```sh
go test -tags=integration -benchtime=10x -timeout=1h -bench . ./test/e2e/benchmark/...
```
Example of command to run test for 1h:
```sh
go test -tags=integration -benchtime=1h -timeout=2h -bench . ./test/e2e/benchmark/...
```

test: benchmark e2e install scenario

---

internal/controller/constants/images.go
internal/controller/rekor/actions/backfillRedis/backfill_redis_cronjob.go

Small pr to update the flags for backfill-redis, to match the latest changes in the latest upstream version

SECURESIGN-1716 | Update Backfill redis flags 

---

internal/controller/rekor/actions/server/deployment.go

This is to prevent errors when storing attestations such like this (which lead to the attestation not being stored at all):
```
2025-02-12T08:25:38.400Z	DEBUG api/entries.go:277	error storing attestation: blob (key "sha256:63e103a30619b9bb47acc8e28c476072f785329bdb7897bb93a642be48651719") (code=Unknown): rename /tmp/sha256:63e103a30619b9bb47acc8e28c476072f785329bdb7897bb93a642be48651719.182368764cd52996.tmp /var/run/attestations/sha256:63e103a30619b9bb47acc8e28c476072f785329bdb7897bb93a642be48651719: invalid cross-device link	{"operation": {"id": "rekor-server-7f846b7fdc-xtxfz/u5fdJYde07-000449"}}
```

[SECURESIGN-1891] Fix configuration of attestation storage so Rekor can actually store attestations

---

.github/workflows/main.yml

Small pr to fix Replace images in the ci, for context:
Due to changes in how we pass in images to the operator, running `make dev-images && cat internal/images/images.env` after the operator was deployed meant that we would be passing in `registry.redhat.io` coords instead of `quay.io` in pr's like this one https://github.com/securesign/secure-sign-operator/pull/898, leading to the ci trying to pull images that didn't exist yet

Fix Replace images in ci

---

test/e2e/support/common.go

- retrieves logs from every pod in the given namespace
- adds each log file to a zip folder under "pod-logs/"

feat(retrievePodLogs): fetch logs from pods and add to zip 

---

Makefile
bundle/manifests/rhtas-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/rhtas-operator.clusterserviceversion.yaml

| registry.redhat.io/rhtas/rhtas-rhel9-operator | c9da046 | c83249b |
---

:robot: [RHTAS-build-bot] [main] Update Operator Bundle Controller Image

---

test/e2e/custom_install/proxy.go

Fixes instability of proxy e2e test which has been caused by DockerHub pull limit.

test: use grc mirror to pull httpd image

---

bundle.Dockerfile

change component and name labels values to rhtas-operator-bundle
Reference:
- https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md
- https://github.com/konflux-ci/olm-operator-konflux-sample/blob/main/Containerfile.gatekeeper-operator-bundle

fix: build bundle image from scratch

---

internal/controller/securesign/actions/ensure_tsa.go
internal/controller/securesign/actions/update_status.go

Fixing regression which caused panic error when TSA configuration is nil in Securesign resource.
Error message in operator log:
```
E0318 11:22:04.856291       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 594 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x18d2f60, 0x2bd8c70})
/cachi2/output/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000585340?})
/cachi2/output/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x18d2f60?, 0x2bd8c70?})
/usr/lib/golang/src/runtime/panic.go:785 +0x132 …
```

fix: panic error when TSA configuration is nil in Securesign resource

---

Dockerfile.rhtas-operator.rh
bundle.Dockerfile

https://docs.redhat.com/en/documentation/red_hat_software_certification/2025/html-single/red_hat_openshift_software_certification_policy_guide/index#con-image-content-requirements_openshift-sw-cert-policy-container-images

fix: container images to include OS licensing at /licenses

---

.github/release.yaml

I am adding an configuration to filter changes from autogenerated release notes.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

ci: add configuration for generated release notes

---

.github/release.yaml

Fixes red-hat-konflux and openshift-merge-bot accounts names. 
Output of autogenerated changelog which correctly excluded konflux bot PRs
```
* [SECURESIGN-1529] Keep url status up-to-date by @bouskaJ in https://github.com/securesign/secure-sign-operator/pull/787
* [SECURESIGN-1891] Fix configuration of attestation storage so Rekor can actually store attestations by @bkabrda in https://github.com/securesign/secure-sign-operator/pull/852
* fix: Add missing flag for RELATED_IMAGE_TRILLIAN_CREATE_TREE by @osmman in https://github.com/securesign/secure-sign-operator/pull/926
* fix: mount kubernetes api server certificate to /var/run/fulcio/ca.crt by @osmman in https://github.com/securesign/secure-sign-operator/pull/932
* fix: build bundle image from scratch by @osmman in …
```

fix: excluded bot account in .github/release.yaml

---

cmd/main.go
go.mod
go.sum
internal/controller/common/utils/kubernetes/ensure/ensure_test.go
internal/controller/common/utils/kubernetes/service_moniter.go
internal/controller/common/utils/kubernetes/service_moniter_test.go
internal/controller/ctlog/actions/monitoring.go
internal/controller/fulcio/actions/monitoring.go
internal/controller/rekor/actions/server/monitoring.go
internal/controller/trillian/actions/logserver/monitoring.go
internal/controller/trillian/actions/logsigner/monitoring.go
internal/controller/tsa/actions/monitoring.go
internal/testing/action/support.go
test/e2e/support/common.go

Change to use unstructured api to operate with SecureMonitor resources.

refactor: remove prometheus-operator dependency

---

docs/rekor-key-rotation.md
internal/controller/rekor/actions/server/generate_signer.go

Downgrading EC param of the autogenerated rekor key. This makes it so that we are using a legit compatible signature algorithm instead of the current P385/SHA256 which leads to security issues due to ending bits not being verified properly unless a client has fallbacks and backwards compatibility.
```
"tlogs": [
{
"baseUrl": "https://rekor.rhtas",
"hashAlgorithm": "SHA2_256",
"publicKey": {
"rawBytes": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwL+jPygzKH7x1IUVEc97LV3qnYe3aPHLucs21SC5VOioYl4cTe0ZBStjle7ITGaRDhtHNFQo9FEI0KoGwe8iLQ==",
"keyDetails": "PKIX_ECDSA_P256_SHA_256",
"validFor": {
"start": "2025-06-11T14:12:39Z"
}
},
"logId": {
"keyId": "m1CTl3vJkYhrNYcKxFLIH7cq4lIPCYHIcR2HQQZCOMo="
}
}
],
```
Shows the correct keyDetails now and works. Signed + verified using the model transparency …

fix: downgrading autogenerated rekor key to P256

---

config/samples/rhtas_v1alpha1_securesign.yaml
config/samples/rhtas_v1alpha1_timestampauthority.yaml

A library I am working with for model signing is extremely strict with self signed CA's, and will not allow them whatsoever. This change makes it possible for TAS to work out the box with no issues.

fix: changing CA common names

---

internal/utils/kubernetes/config_map_test.go
internal/utils/kubernetes/ensure/deployment/deployment_test.go
internal/utils/kubernetes/ingress_test.go
internal/utils/kubernetes/pvc_test.go
internal/utils/kubernetes/role_binding_test.go
internal/utils/kubernetes/role_test.go
internal/utils/kubernetes/secret_test.go
internal/utils/kubernetes/service_test.go
internal/utils/tls/tls_test.go

Tests
___
- Replace global gomega registration with per-test instances
- Fix assertion logic in config map tests
- Improve test isolation and thread safety
___
```mermaid
flowchart LR
A["gomega.RegisterTestingT(t)"] --> B["gomega.NewWithT(t)"]
B --> C["g.Expect() calls"]
D["Global gomega"] --> E["Per-test gomega"]
F["Fixed assertions"] --> G["Better test isolation"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><details><summary>10 files</summary><table>
<tr>
<td><strong>config_map_test.go</strong><dd><code>Replace global gomega with per-test instance</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

test: wrap a testing.T by gomega.WithT
